# Generated by Django 3.0.4 on 2020-04-24 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegularPizzaPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Base_price_sm', models.FloatField(default=12.7)),
                ('Base_price_lg', models.FloatField(default=17.95)),
                ('toppings1_sm', models.FloatField(default=13.7)),
                ('toppings1_lg', models.FloatField(default=19.95)),
                ('toppings2_sm', models.FloatField(default=15.2)),
                ('toppings2_lg', models.FloatField(default=21.95)),
                ('toppings3_sm', models.FloatField(default=16.2)),
                ('toppings3_lg', models.FloatField(default=23.95)),
                ('special_sm', models.FloatField(default=17.75)),
                ('special_lg', models.FloatField(default=25.95)),
            ],
        ),
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegularPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Base', models.CharField(default='Cheese', editable=False, max_length=64)),
                ('items_1', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='toppings', to='orders.Toppings')),
                ('items_2', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='toppings2', to='orders.Toppings')),
                ('items_3', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='toppings3', to='orders.Toppings')),
                ('special', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='specials', to='orders.Toppings')),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('pizza_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.RegularPizza')),
            ],
        ),
    ]
