# Generated by Django 3.0.4 on 2020-04-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='default',
            field=models.CharField(default='Hello', editable=False, max_length=64),
        ),
    ]
