# Generated by Django 3.0.4 on 2020-04-24 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_toppings_special'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
