# Generated by Django 3.0.5 on 2020-04-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_delete_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toppings',
            name='special',
            field=models.BooleanField(default=False),
        ),
    ]
