# Generated by Django 3.0.5 on 2020-04-27 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200427_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toppings',
            old_name='name',
            new_name='items',
        ),
    ]
