# Generated by Django 3.0.5 on 2020-04-27 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200427_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularpizza',
            name='items_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toppings', to='orders.Toppings'),
        ),
        migrations.AlterField(
            model_name='regularpizza',
            name='items_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toppings2', to='orders.Toppings'),
        ),
        migrations.AlterField(
            model_name='regularpizza',
            name='items_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toppings3', to='orders.Toppings'),
        ),
        migrations.AlterField(
            model_name='regularpizza',
            name='special',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specials', to='orders.Toppings'),
        ),
    ]
