# Generated by Django 3.0.5 on 2020-04-28 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20200427_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('special', models.BooleanField(default=False)),
                ('f_category', models.CharField(choices=[('Toppings', 'Tops'), ('Subs', 'Subs'), ('Pasta', 'Pasta'), ('Salad', 'Salad'), ('Dinner', 'Dine')], max_length=25)),
                ('m_category', models.CharField(choices=[('Regular', 'Reg'), ('Sicillian', 'Sic')], max_length=25)),
                ('Price', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Base', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Base', to='orders.Menu')),
                ('Other', models.ManyToManyField(to='orders.Menu')),
                ('Special', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='special_item', to='orders.Menu')),
                ('item_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_1', to='orders.Menu')),
                ('item_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_2', to='orders.Menu')),
                ('item_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_3', to='orders.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile_orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.ManyToManyField(to='orders.Cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='customers',
            name='pizza_1',
        ),
        migrations.RemoveField(
            model_name='regularpizza',
            name='items_1',
        ),
        migrations.RemoveField(
            model_name='regularpizza',
            name='items_2',
        ),
        migrations.RemoveField(
            model_name='regularpizza',
            name='items_3',
        ),
        migrations.RemoveField(
            model_name='regularpizza',
            name='special',
        ),
        migrations.DeleteModel(
            name='RegularPizzaPrice',
        ),
        migrations.DeleteModel(
            name='Customers',
        ),
        migrations.DeleteModel(
            name='RegularPizza',
        ),
        migrations.DeleteModel(
            name='Toppings',
        ),
        migrations.AddField(
            model_name='cart',
            name='stuff',
            field=models.ManyToManyField(to='orders.Order'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Profile'),
        ),
    ]
