# Generated by Django 3.0.5 on 2020-04-28 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20200428_0839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='f_category',
            new_name='foodcategory',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='m_category',
            new_name='menucategory',
        ),
    ]
