# Generated by Django 3.0.5 on 2020-04-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20200428_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='Price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menucategory',
            field=models.CharField(choices=[('Regular', 'Reg'), ('Sicillian', 'Sic'), ('Others', 'Others')], max_length=25),
        ),
    ]
