# Generated by Django 3.0.5 on 2020-04-28 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20200428_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Base_small', models.FloatField()),
                ('item_1_small', models.FloatField()),
                ('item_2_small', models.FloatField()),
                ('item_3_small', models.FloatField()),
                ('Special_small', models.FloatField()),
                ('Base_large', models.FloatField()),
                ('item_1_large', models.FloatField()),
                ('item_2_large', models.FloatField()),
                ('item_3_large', models.FloatField()),
                ('Special_large', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SicillianPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Base_small', models.FloatField()),
                ('item_1_small', models.FloatField()),
                ('item_2_small', models.FloatField()),
                ('item_3_small', models.FloatField()),
                ('Special_small', models.FloatField()),
                ('Base_large', models.FloatField()),
                ('item_1_large', models.FloatField()),
                ('item_2_large', models.FloatField()),
                ('item_3_large', models.FloatField()),
                ('Special_large', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='Base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Base', to='orders.Menu'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Special',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='special_item', to='orders.Menu'),
        ),
        migrations.AlterField(
            model_name='order',
            name='item_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_1', to='orders.Menu'),
        ),
        migrations.AlterField(
            model_name='order',
            name='item_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_2', to='orders.Menu'),
        ),
        migrations.AlterField(
            model_name='order',
            name='item_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_3', to='orders.Menu'),
        ),
    ]
