# Generated by Django 3.0.5 on 2020-04-28 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20200428_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Base',
            field=models.ForeignKey(blank=True, default='cheese', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Base', to='orders.Menu'),
        ),
    ]
