# Generated by Django 3.0.5 on 2020-04-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20200428_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='order_total',
            field=models.FloatField(default=0.0),
        ),
    ]
