# Generated by Django 3.0.5 on 2020-04-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_cart_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
