# Generated by Django 3.0.5 on 2020-04-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_auto_20200428_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='stuff',
            field=models.ManyToManyField(blank=True, null=True, to='orders.Order'),
        ),
    ]
