# Generated by Django 3.0.5 on 2020-05-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_auto_20200428_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='foodcategory',
            field=models.CharField(choices=[('Toppings', 'Tops'), ('Subs', 'Subs'), ('Pasta', 'Pasta'), ('Salad', 'Salad'), ('Dinner', 'Dine'), ('Base', 'base')], max_length=25),
        ),
    ]
