# Generated by Django 3.0.5 on 2020-05-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_auto_20200502_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='Price_large',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='Price_small',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='Price',
            field=models.FloatField(blank=True, choices=[('small', models.FloatField(blank=True, null=True)), ('large', models.FloatField(blank=True, null=True))], null=True),
        ),
    ]
