# Generated by Django 3.0.5 on 2020-05-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_remove_menu_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='order_total',
            new_name='Total',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Other',
        ),
        migrations.AddField(
            model_name='order',
            name='order_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menucategory',
            field=models.CharField(choices=[('Regular', 'Reg'), ('Sicillian', 'Sic'), ('Subs', 'subs'), ('Pasta', 'pas'), ('Salad', 'sal'), ('Dinner', 'Dine')], max_length=25),
        ),
    ]
