# Generated by Django 3.0.5 on 2020-05-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_auto_20200515_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Others',
            field=models.ManyToManyField(blank=True, null=True, related_name='Others', to='orders.Menu'),
        ),
    ]
