# Generated by Django 3.0.5 on 2020-05-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_order_others'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Others',
            field=models.ManyToManyField(related_name='Others', to='orders.Menu'),
        ),
    ]
