# Generated by Django 3.0.6 on 2020-05-24 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_auto_20200515_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_orders',
            name='orders',
        ),
        migrations.RemoveField(
            model_name='profile_orders',
            name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='Base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Base', to='orders.Menu'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Others',
            field=models.ManyToManyField(to='orders.Menu'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Profile_orders',
        ),
    ]
