# Generated by Django 3.0.6 on 2020-05-31 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_auto_20200524_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=64)),
                ('City', models.CharField(max_length=32)),
                ('Postal_Code', models.CharField(max_length=32)),
                ('Telephone', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='Ship_Add',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Shipping_address', to='orders.AddressBook'),
        ),
    ]
