# Generated by Django 3.0.6 on 2020-05-31 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_auto_20200531_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addressbook',
            old_name='address',
            new_name='Address',
        ),
    ]
